# -*- coding: utf-8 -*-
"""속도 측정기..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3Ubci7Hlhw4qqcLTq1v_6ME8TX2yPhR
"""

import gradio as gr
import cv2
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

def calc(img1_path, img2_path, time_interval, input_distance):
    if img1_path is None or img2_path is None:
        return None, "substance: -\ntravel distance: -\nspeed: -", "import 2 images."

    STANDARD_DISTANCE = 1.0
    STANDARD_PIXEL_SIZE = 100.0

    ps= STANDARD_PIXEL_SIZE * (STANDARD_DISTANCE / float(input_distance))


    results = model(img2_path)

    for result in results:
        boxes = result.boxes
        if len(boxes) > 0:
            box = boxes[0]
            x1, y1, x2, y2 = box.xyxy[0].tolist()

            current_pixel_size = max(x2 - x1, y2 - y1)

            estimated_distance_2 = float(input_distance) * (ps/ current_pixel_size)
            moved_distance = abs(estimated_distance_2 - float(input_distance))
            speed = moved_distance / float(time_interval)

            detected_label = model.names[int(box.cls[0])]


            results_summary = (
                f"substance : {detected_label}\n"
                f"travel distance : {moved_distance:.2f} m\n"
                f"speed : {speed:.2f} m/s"
            )


            res_bgr = result.plot()
            res_rgb = cv2.cvtColor(res_bgr, cv2.COLOR_BGR2RGB)

            return res_rgb, results_summary

    return None, "substance: -\ntravel distance: -\nspeed: -", "couldn't detect substance."

with gr.Blocks(title="Speedometer") as demo:
    gr.Markdown("# **Rhyl** Speedometer")

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### 1. Upload 2 Pictures")

            gr.Markdown("### 2. Time between 2 Pictures")
            time_input = gr.Number(value=0.7, label="", info="단위: (s)")

            gr.Markdown("### 3. Distance between the camera and the substance")
            dist_input = gr.Number(value=0.3, label="", info="단위: (m)")

            btn = gr.Button(" Calculate", variant="primary")

        with gr.Column(scale=2):
            img1 = gr.Image(type="filepath", label="First Picture (+)", height=200)
            img2 = gr.Image(type="filepath", label="Second Picture (+)", height=200)

            gr.Markdown("### Results")
            output_img = gr.Image(label="Detection Image", height=200)
            output_text = gr.Textbox(label="", lines=4)

    btn.click(
        fn=calc,
        inputs=[img1, img2, time_input, dist_input],
        outputs=[output_img, output_text]
    )

demo.launch()
